export type Nota = {
  nome: String;
  documento: String;
  email: String;
  telefone: String;
  cep: String;
  logradouro: String;
  numero: String;
  bairro: String;
  cidade: String;
  uf: String;
  id: String;
  clientId: String;
  data: String;
  marca: String;
  modelo: String;
  ano: String;
  km: String;
  detalhes: String;
  valorServico: String;
  valorProduto: String;
  valorTotal: String;
  servicosPrestados: String;
};
